# Generated by Django 5.0.1 on 2024-02-02 09:13

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=30)),
                ('data', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=10)),
                ('topic', models.CharField(max_length=20)),
                ('heading', models.CharField(max_length=50)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
    ]
